#
# Module manifest for module 'ParallelExecution'
#
# Generated by: OpenTofu Lab Automation Team
#
# Generated on: 6/17/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ParallelExecution.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = '12345678-90ab-cdef-1234-567890abcdef'

# Author of this module
Author = 'OpenTofu Lab Automation Team'

# Company or vendor of this module
CompanyName = 'wizzense'

# Copyright statement for this module
Copyright = '(c) wizzense. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Parallel processing utilities for OpenTofu Lab Automation'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '7.0'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Invoke-ParallelForEach',
    'Start-ParallelJob',
    'Wait-ParallelJobs',
    'Invoke-ParallelPesterTests',
    'Merge-ParallelTestResults'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Parallel', 'Performance', 'Testing', 'PowerShell', 'CrossPlatform')

        # A URL to the license for this module.
        LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = ''

        # A URL to an icon representing this module.
        IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Initial release with parallel processing capabilities'

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
